##------------------------------------------------------------------------------
## Bobae's MA Thesis (github.com/bobaekang/MA_thesis)            
## Researcher: Bobae Kang (github.com/bobaekang)                 
## Advisor: Benjamin Soltoff (github.com/bensoltoff)             
##------------------------------------------------------------------------------
## Script: thesis03_sample_generation.R                                    
## Last updated: 5/1/17                                         
##------------------------------------------------------------------------------
## This script performs the following tasks:                     
## 1. reading in the Divvy trip and CTA route data generated by the previous
## script, as well as the Divvy station data with various proximity indicators
## and construct functions to add multi-modal variables to the Divvy trip data                  
## 2. adding binary and non-binary multi-model variables to Divvy trip data
## for various proximity standards (50m, 100m, 200m, and 300m)                                   
## 3. Save outputs                                         
##------------------------------------------------------------------------------
## This script requires the outputs from the following scripts:  
## * thesis01_prepare1.R 
## * thesis02_prepare2.R
##------------------------------------------------------------------------------

# Load packages
library(tidyverse)
library(feather)
library(lubridate)
library(stringr)
library(feather)


##------------------------------------------------------------------------------
## 1. READ DATA AND DEFINE FUNCTIONS
## The following codes read data and define necessary functions
##------------------------------------------------------------------------------
set.seed(2017)

## 1.0. Import and prepare the data---------------------------------------------
# Read in and prepare data for tidying
divvy_data            <- read_feather("data/Divvy_data.feather")
cta_stop_times_loc    <- read_feather("data/CTA_stop_times_location.feather")
divvy_station50       <- read_feather("data/stops_within_50m.feather")
divvy_station100      <- read_feather("data/stops_within_100m.feather")
divvy_station200      <- read_feather("data/stops_within_200m.feather")
divvy_station300      <- read_feather("data/stops_within_300m.feather")
divvy_station_geodemo <- read_feather("data/Divvy_station_geodemo.feather")

# clean Divvy station data
divvy_station_clean <- divvy_station_geodemo %>%
  filter(cca_id != 'NA') %>%                                                 # remove 23 stations outside Chicago
  select(-c(divvy_ix, area, population, employed, pop_density, emp_density)) # remove irrelevant columns

# clean Divvy trip data
divvy_data_clean <- divvy_data %>%
  filter(usertype != 'Dependent',                   # remove 'Dependent' usertype
         tripduration    <= 90*60,                  # remove trips longer than 90 mins
         from_station_id != to_station_id,          # remove trips with the same origin and destination
         from_station_id != divvy_station_clean$id, # remove trips began outside Chicago
         to_station_id   != divvy_station_clean$id) # remove trips ended outside Chicago 

# Divvy trip times, divided into from and to
divvy_from <- divvy_data_clean %>%
  # filter(onemile == 1) %>%      # only trips that are shorter than a mile
  select(-c(stoptime, to_station_id, to_station_name, to_lon, to_lat,
            to_prox50, to_prox50_n, to_prox100, to_prox100_n,
            to_prox200, to_prox200_n, to_prox300, to_prox300_n,
            stopdate, stophour, stoprush))
divvy_to <- divvy_data_clean %>%
  # filter(onemile == 1) %>%                                                     # only trips that are shorter than a mile
  select(-c(starttime, from_station_id, from_station_name, from_lon, from_lat, # remove irrelevant columns
            from_prox50, from_prox50_n, from_prox100, from_prox100_n,
            from_prox200, from_prox200_n, from_prox300, from_prox300_n,
            startdate, starthour, startrush))

# CTA times, divided into arrivals and departures
cta_arrivals <- cta_stop_times_loc %>%
  select(arrival_time, stop_id)
cta_departures <- cta_stop_times_loc %>%
  select(departure_time, stop_id)


## 1.1. Define functions--------------------------------------------------------
# Functions to add multimode and multimode_n
# Divvy from and CTA departure
multimodalFrom <- function(from_input, departures_input){
  # join divvy trips and cta routes data (it gets very large!)
  data <- left_join(from_input, departures_input)
  
  # create array of (hour, minute, second)
  depart_array <- t(array(as.numeric(unlist(strsplit(data$departure_time, split=':'))),
                          dim = c(3, nrow(data))))
  start_array <- t(array(as.numeric(unlist(strsplit(data$starthour, split=':'))),
                         dim = c(2, nrow(data))))
  
  # get vector of time in seconds
  depart_vec <- depart_array[,1]*3600 + depart_array[,2]*60 + depart_array[,3]
  start_vec <- start_array[,1]*3600 + start_array[,2]*60
  # get vector of time difference in seconds: time Divvy starts - time CTA departs 
  diff_vec <- (start_vec - depart_vec)
  
  # add a colume of 'close' trips
  data$close <- ((300 >= diff_vec & 60 < diff_vec) |
                   (86340 > diff_vec & 86100 <= diff_vec))*1
  
  close_var <- data %>%
    group_by(trip_id) %>%
    summarise(multimode_n = sum(close == 1, na.rm = TRUE))
  close_var$multimode <- as.logical(close_var$multimode_n)*1
  output <- from_input %>% left_join(close_var)
  
  # change multi-mode variables to 0 if longtrip == 0
  output$multimode <- ifelse(output$longtrip == 0, output$multimode, 0)
  output$multimode_n <- ifelse(output$longtrip == 0, output$multimode_n, 0)
  
  return(output)
}


# Divvy to and CTA arrival
multimodalTo <- function(to_input, arrivals_input){
  # join divvy trips and cta routes data (it gets very large!)
  data <- left_join(to_input, arrivals_input)
  
  # create array of (hour, minute, second)
  arrive_array <- t(array(as.numeric(unlist(strsplit(data$arrival_time, split=':'))),
                          dim = c(3, nrow(data))))
  stop_array <- t(array(as.numeric(unlist(strsplit(data$stophour, split=':'))),
                         dim = c(2, nrow(data))))
  
  # get vector of time in seconds
  arrive_vec <- arrive_array[,1]*3600 + arrive_array[,2]*60 + arrive_array[,3]
  stop_vec <- stop_array[,1]*3600 + stop_array[,2]*60
  # get vector of time difference in seconds: time CTA arrives - time Divvy stoped
  diff_vec <- (stop_vec - arrive_vec)
  
  # add a colume of 'close' trips
  data$close <- ((300 >= diff_vec & 60 < diff_vec) |
                   (86340 > diff_vec & 86100 <= diff_vec))*1
  
  close_var <- data %>%
    group_by(trip_id) %>%
    summarise(multimode_n = sum(close == 1, na.rm = TRUE))
  close_var$multimode <- as.logical(close_var$multimode_n)*1
  output <- to_input %>% left_join(close_var)
  
  # change multi-mode variables to 0 if longtrip == 0
  output$multimode <- ifelse(output$longtrip == 0, output$multimode, 0)
  output$multimode_n <- ifelse(output$longtrip == 0, output$multimode_n, 0)
  
  return(output)
}

##------------------------------------------------------------------------------
## 2. ADD MULTI-MODAL VARIABLES FOR PROXIMITY <50m, <100m, <200m and <300m
## The following codes adds multi-modal variables for proximity < 50m
##------------------------------------------------------------------------------

## 2.0. Prepare the samples-----------------------------------------------------
# Divvy statons and CTA stops in proximity 
# (<50m)
prox50 <- divvy_station50 %>%
  filter(prox50 == 1) %>%
  left_join(divvy_station_clean)
# (<100m)  
prox100 <- divvy_station100 %>%
  filter(prox100 == 1) %>%
  left_join(divvy_station_clean)
# (<200m)  
prox200 <- divvy_station200 %>%
  filter(prox200 == 1) %>%
  left_join(divvy_station_clean)
# (<300m)  
prox300 <- divvy_station300 %>%
  filter(prox300 == 1) %>%
  left_join(divvy_station_clean)

# CTA arrivals to and departures from CTA stops that are in proximity with Divvy stations 
# (<50m) 
cta_arrivals50             <- left_join(prox50, cta_arrivals) %>% select(-name)
colnames(cta_arrivals50)   <- c('to_station_id', colnames(cta_arrivals50)[2:ncol(cta_arrivals50)])
cta_departures50           <- left_join(prox50, cta_departures) %>% select(-name)
colnames(cta_departures50) <- c('from_station_id', colnames(cta_departures50)[2:ncol(cta_departures50)])
# (<100m) 
cta_arrivals100             <- left_join(prox100, cta_arrivals) %>% select(-name)
colnames(cta_arrivals100)   <- c('to_station_id', colnames(cta_arrivals100)[2:ncol(cta_arrivals100)])
cta_departures100           <- left_join(prox100, cta_departures) %>% select(-name)
colnames(cta_departures100) <- c('from_station_id', colnames(cta_departures100)[2:ncol(cta_departures100)])
# (<200m)
cta_arrivals200             <- left_join(prox200, cta_arrivals) %>% select(-name)
colnames(cta_arrivals200)   <- c('to_station_id', colnames(cta_arrivals200)[2:ncol(cta_arrivals200)])
cta_departures200           <- left_join(prox200, cta_departures) %>% select(-name)
colnames(cta_departures200) <- c('from_station_id', colnames(cta_departures200)[2:ncol(cta_departures200)])
# (<300m)
cta_arrivals300             <- left_join(prox300, cta_arrivals) %>% select(-name)
colnames(cta_arrivals300)   <- c('to_station_id', colnames(cta_arrivals300)[2:ncol(cta_arrivals300)])
cta_departures300           <- left_join(prox300, cta_departures) %>% select(-name)
colnames(cta_departures300) <- c('from_station_id', colnames(cta_departures300)[2:ncol(cta_departures300)])

# Sample of N = 20,000
from_sample <- sample_n(divvy_from, 20000)
to_sample  <- sample_n(divvy_to, 20000)

# free up some memory
rm(divvy_data, divvy_data_clean, divvy_from, divvy_to,
   divvy_station_clean, divvy_station_geodemo,
   cta_departures, cta_arrivals, cta_stop_times_loc,
   divvy_station50, divvy_station100, divvy_station200, divvy_station300,
   prox50, prox100, prox200, prox300)
gc()
 
## 2.1. Add multi-modal variables-----------------------------------------------
# (<50m)
divvy_from50_sample  <- multimodalFrom(from_sample, cta_departures50)
divvy_to50_sample    <- multimodalTo(to_sample, cta_arrivals50)
# free up some memory
rm(cta_departures50, cta_arrivals50)
gc()

# (<100m)
divvy_from100_sample <- multimodalFrom(from_sample, cta_departures100)
divvy_to100_sample   <- multimodalTo(to_sample, cta_arrivals100)
# free up some memory
rm(cta_departures100, cta_arrivals100)
gc()

# (<200m)
divvy_from200_sample <- multimodalFrom(from_sample, cta_departures200)
divvy_to200_sample   <- multimodalTo(to_sample, cta_arrivals100)
# free up some memory
rm(cta_departures200, cta_arrivals200)
gc()

# (<300m)
divvy_from300_sample <- multimodalFrom(from_sample, cta_departures300)
divvy_to300_sample   <- multimodalTo(to_sample, cta_arrivals300)
# free up some memory
rm(cta_departures300, cta_arrivals300)
gc()


##------------------------------------------------------------------------------
## 3. SAVE OUTPUTS
##------------------------------------------------------------------------------
# (<50m)
write_feather(divvy_from50_sample, 'data/divvy_from50_sample.feather')
write_feather(divvy_to50_sample, 'data/divvy_to50_sample.feather')

# (<100m)
write_feather(divvy_from100_sample, 'data/divvy_from100_sample.feather')
write_feather(divvy_to100_sample, 'data/divvy_to100_sample.feather')

# (<200m)
write_feather(divvy_from200_sample, 'data/divvy_from200_sample.feather')
write_feather(divvy_to200_sample, 'data/divvy_to200_sample.feather')

# (<300m)
write_feather(divvy_from300_sample, 'data/divvy_from300_sample.feather')
write_feather(divvy_to300_sample, 'data/divvy_to300_sample.feather')

# Clear the environment---------------------------------------------------------
rm(list=ls()) # clear the environment
