##---------------------------------------------------------------##
## Bobae's MA Thesis (github.com/bobaekang/MA_thesis)            ##
## Researcher: Bobae Kang (github.com/bobaekang)                 ##
## Advisor: Benjamin Soltoff (github.com/bensoltoff)             ##
##---------------------------------------------------------------##
## Script: thesis02_prepare.R                                    ##
## Last updated: 3/24/17                                         ##
##---------------------------------------------------------------##
## This script performs the following tasks:                     ##
## 1. reading in the Divvy trip and CTA route data generated by  ##
## the previous script, as well as the Divvy station data with   ##
## various proximity indicators and construct functions to add   ##
## muldi-modal variables to the Divvy trip data                  ##
## 2-5. adding binary and non-binary multi-model variables to    ##
## Divvy trip data for various proximity standards               ##
## (50m, 100m, 200m, and 300m)                                   ##
## 6. Save outputs                                               ##
##---------------------------------------------------------------##
## This script requires the outputs from the following scripts:  ##
## * thesis01_prepare1.R                                         ##
##---------------------------------------------------------------##

# Load packages
library(tidyverse)
library(feather)
library(lubridate)
library(fasttime)
library(stringr)
library(feather)


##--------------------------------------------------------------------------------------------------##
## 1. READ DATA AND DEFINE FUNCTIONS
## The following codes read data and define necessary functions
##--------------------------------------------------------------------------------------------------##

## 1.0. Import and prepare the data-----------------------------------------------------------------##
# Read in and prepare data for tidying
divvy_data         <- read_feather("data/Divvy_data.feather")
cta_stop_times_loc <- read_feather("data/CTA_stop_times_location.feather")
divvy_station50    <- read_feather("data/stops_within_50m.feather")
divvy_station100   <- read_feather("data/stops_within_100m.feather")
divvy_station200   <- read_feather("data/stops_within_200m.feather")
divvy_station300   <- read_feather("data/stops_within_300m.feather")


# Divvy trip times, divided into from and to
divvy_from <- divvy_data %>%
  select(-c(stoptime, to_station_id, to_station_name, to_lon, to_lat,
            to_prox50, to_prox50_n, to_prox100, to_prox100_n, to_prox200, to_prox200_n, to_prox300, to_prox300_n,
            stopdate, stophour, stoprush))

divvy_to <- divvy_data %>%
  select(-c(starttime, from_station_id, from_station_name, from_lon, from_lat,
            from_prox50, from_prox50_n, from_prox100, from_prox100_n, from_prox200, from_prox200_n, from_prox300, from_prox300_n,
            startdate, starthour, startrush))

# CTA times, divided into arrivals and departures
cta_arrivals <- cta_stop_times_loc %>%
  select(arrival_time, stop_id)
cta_departures <- cta_stop_times_loc %>%
  select(departure_time, stop_id)


## 1.1. Define functions----------------------------------------------------------------------------##
# Functions to add multimode and multimode_n (using lubiridate::fast_strptime; still too slow)
multimodalFrom <- function(from_input, departures_input){ # for trips that start in a potentially multi-modal manner
  data <- left_join(from_input, departures_input)
  dep <- fast_strptime(str_c(data$startdate, data$departure_time, sep = " "),
                       format = "%Y-%m-%d %H:%M:%OS", tz = "America/Chicago")
  data$close <- (5 >= abs(difftime(dep, data$starttime, tz = "America/Chicago", units = c("mins"))) |
                   1< abs(difftime(dep, data$starttime, tz = "America/Chicago", units = c("mins"))))*1
  
  close_var <- data %>%
    group_by(trip_id) %>%
    summarise(multimode_n = sum(close == 1, na.rm = TRUE))
  close_var$multimode <- as.logical(close_var$multimode_n)*1
  output <- from_input %>% left_join(close_var)
  
  output$multimode <- ifelse(output$longtrip == 0, output$multimode, 0)
  output$multimode_n <- ifelse(output$longtrip == 0, output$multimode_n, 0)

  return(output)
}

multimodalTo <- function(to_input, arrivals_input){ # for trips that end in a potentially multi-modal manner
  data <- left_join(to_input, arrivals_input)
  arr <- fast_strptime(str_c(data$stopdate, data$arrival_time, sep = " "),
                       format = "%Y-%m-%d %H:%M:%OS", tz = "America/Chicago")
  data$close <- (5 >= abs(difftime(data$stoptime, arr, tz = "America/Chicago", units = c("mins"))) |
                   1 < abs(difftime(data$stoptime, arr, tz = "America/Chicago", units = c("mins"))))*1
  
  close_var <- data %>%
    group_by(trip_id) %>%
    summarise(multimode_n = sum(close == 1, na.rm = TRUE))
  close_var$multimode <- as.logical(close_var$multimode_n)*1
  output <- to_input %>% left_join(close_var)

  output$multimode <- ifelse(output$longtrip == 0, output$multimode, 0)
  output$multimode_n <- ifelse(output$longtrip == 0, output$multimode_n, 0)

  return(output)
}

# Functions to add multimode and multimode_n (faster version using R functions)
multimodalFrom1 <- function(from_input, departures_input){ # for trips that start in a potentially multi-modal manner
  # join divvy trips and cta routes data (it gets very large!)
  data <- left_join(from_input, departures_input)
  
  # create array of (hour, minute, second)
  depart_array <- t(array(as.numeric(unlist(strsplit(data$departure_time, split=':'))), dim = c(3, nrow(data))))
  start_array <- t(array(as.numeric(unlist(strsplit(data$starthour, split=':'))), dim = c(2, nrow(data))))
  
  # get vector of time in seconds
  depart_vec <- depart_array[,1]*3600 + depart_array[,2]*60 + depart_array[,3]
  start_vec <- start_array[,1]*3600 + start_array[,2]*60
  # get vector of time difference in seconds
  diff_vec <- abs(depart_vec - start_vec)
  
  # add a colume of 'close' trips
  data$close <- ((300 >= diff_vec & 60 < diff_vec) | (86340 > diff_vec & 86100 <= diff_vec))*1
  
  close_var <- data %>%
    group_by(trip_id) %>%
    summarise(multimode_n = sum(close == 1, na.rm = TRUE))
  close_var$multimode <- as.logical(close_var$multimode_n)*1
  output <- from_input %>% left_join(close_var)
  
  # change multi-mode variables to 0 if longtrip == 0
  output$multimode <- ifelse(output$longtrip == 0, output$multimode, 0)
  output$multimode_n <- ifelse(output$longtrip == 0, output$multimode_n, 0)
  
  return(output)
}

multimodalTo1 <- function(to_input, arrivals_input){ # for trips that end in a potentially multi-modal manner
  # join divvy trips and cta routes data (it gets very large!)
  data <- left_join(to_input, arrivals_input)
  
  # create array of (hour, minute, second)
  depart_array <- t(array(as.numeric(unlist(strsplit(data$departure_time, split=':'))), dim = c(3, nrow(data))))
  start_array <- t(array(as.numeric(unlist(strsplit(data$starthour, split=':'))), dim = c(2, nrow(data))))
  
  # get vector of time in seconds
  depart_vec <- depart_array[,1]*3600 + depart_array[,2]*60 + depart_array[,3]
  start_vec <- start_array[,1]*3600 + start_array[,2]*60
  # get vector of time difference in seconds
  diff_vec <- abs(depart_vec - start_vec)
  
  # add a colume of 'close' trips
  data$close <- ((300 >= diff_vec & 60 < diff_vec) | (86340 > diff_vec & 86100 <= diff_vec))*1
  
  close_var <- data %>%
    group_by(trip_id) %>%
    summarise(multimode_n = sum(close == 1, na.rm = TRUE))
  close_var$multimode <- as.logical(close_var$multimode_n)*1
  output <- from_input %>% left_join(close_var)
  
  # change multi-mode variables to 0 if longtrip == 0
  output$multimode <- ifelse(output$longtrip == 0, output$multimode, 0)
  output$multimode_n <- ifelse(output$longtrip == 0, output$multimode_n, 0)
  
  return(output)
}


##--------------------------------------------------------------------------------------------------##
## 2. ADD MULTI-MODAL VARIABLES FOR PROXIMITY <50m
## The following codes adds multi-modal variables for proximity < 50m
##--------------------------------------------------------------------------------------------------##

## 2.0. Prepare the data----------------------------------------------------------------------------##
# Divvy trips that started at stations in proximity(<50m) with CTA stops  
divvy_from50 <- divvy_from %>%
  filter(from_prox50 == 1)

# Divvy trips that stopped at stations in proximity(<50m) with CTA stops 
divvy_to50 <- divvy_to %>%
  filter(to_prox50 == 1)

# Divvy statons and CTA stops in proximity (<50m)  
prox50 <- divvy_station50 %>%
  filter(prox50 == 1)

# CTA arrivals to and departures from CTA stops that are in proximity(<50m) with Divvy stations 
cta_arrivals50             <- left_join(prox50, cta_arrivals) %>% select(-name)
colnames(cta_arrivals50)   <- c('to_station_id', colnames(cta_arrivals50)[2:6])
cta_departures50           <- left_join(prox50, cta_departures) %>% select(-name)
colnames(cta_departures50) <- c('from_station_id', colnames(cta_departures50)[2:6])


## 2.1. Add multi-modal variables-------------------------------------------------------------------##
# Use smaller samples (joined data gets too large!)
# from50_sample       <- sample_n(divvy_from50, 10000)
# to50_sample         <- sample_n(divvy_to50, 10000)
# divvy_from50_sample <- multimodalFrom1(from50_sample, cta_departures50)
# divvy_to50_sample   <- multimodalTo1(to50_sample, cta_departures50)

##--------------------------------------------------------------------------------------------------##
## 3. ADD MULTI-MODAL VARIABLES FOR PROXIMITY <100m
## The following codes adds multi-modal variables for proximity < 100m
##--------------------------------------------------------------------------------------------------##

## 3.0. Prepare the data----------------------------------------------------------------------------##
# Divvy trips that started at stations in proximity(<100m) with CTA stops  
divvy_from100 <- divvy_from %>%
  filter(from_prox100 == 1)

# Divvy trips that stopped at stations in proximity(<100m) with CTA stops 
divvy_to100 <- divvy_to %>%
  filter(to_prox100 == 1)

# Divvy statons and CTA stops in proximity (<100m)  
prox100 <- divvy_station100 %>%
  filter(prox100 == 1)

# CTA arrivals to and departures from CTA stops that are in proximity(<100) with Divvy stations 
cta_arrivals100             <- left_join(prox100, cta_arrivals) %>% select(-name)
colnames(cta_arrivals100)   <- c('to_station_id', colnames(cta_arrivals100)[2:6])
cta_departures100           <- left_join(prox100, cta_departures) %>% select(-name)
colnames(cta_departures100) <- c('from_station_id', colnames(cta_departures100)[2:6])

# Use smaller samples (joined data gets too large!)
# from100_sample       <- sample_n(divvy_from100, 10000)
# to100_sample         <- sample_n(divvy_to100, 10000)
# divvy_from100_sample <- multimodalFrom1(from100_sample, cta_departures100)
# divvy_to100_sample   <- multimodalTo1(to100_sample, cta_departures100)


##--------------------------------------------------------------------------------------------------##
## 4. ADD MULTI-MODAL VARIABLES FOR PROXIMITY <200m
## The following codes adds multi-modal variables for proximity < 200m
##--------------------------------------------------------------------------------------------------##

## 4.0. Prepare the data----------------------------------------------------------------------------##
# Divvy trips that started at stations in proximity(<200m) with CTA stops  
divvy_from200 <- divvy_from %>%
  filter(from_prox200 == 1)

# Divvy trips that stopped at stations in proximity(<200m) with CTA stops 
divvy_to200 <- divvy_to %>%
  filter(to_prox200 == 1)

# Divvy statons and CTA stops in proximity (<200m)  
prox200 <- divvy_station200 %>%
  filter(prox200 == 1)

# CTA arrivals to and departures from CTA stops that are in proximity(<200m) with Divvy stations 
cta_arrivals200             <- left_join(prox200, cta_arrivals) %>% select(-name)
colnames(cta_arrivals200)   <- c('to_station_id', colnames(cta_arrivals200)[2:6])
cta_departures200           <- left_join(prox200, cta_departures) %>% select(-name)
colnames(cta_departures200) <- c('from_station_id', colnames(cta_departures200)[2:6])

# Use smaller samples (joined data gets too large!)
# from200_sample       <- sample_n(divvy_from200, 10000)
# to200_sample         <- sample_n(divvy_to200, 10000)
# divvy_from200_sample <- multimodalFrom1(from200_sample, cta_departures200)
# divvy_to200_sample   <- multimodalTo1(to200_sample, cta_departures200)


##--------------------------------------------------------------------------------------------------##
## 5. ADD MULTI-MODAL VARIABLES FOR PROXIMITY <300m
## The following codes adds multi-modal variables for proximity < 300m
##--------------------------------------------------------------------------------------------------##

## 5.0. Prepare the data----------------------------------------------------------------------------##
# Divvy trips that started at stations in proximity(<300m) with CTA stops  
divvy_from300 <- divvy_from %>%
  filter(from_prox300 == 1)

# Divvy trips that stopped at stations in proximity(<300m) with CTA stops 
divvy_to300 <- divvy_to %>%
  filter(to_prox300 == 1)

# Divvy statons and CTA stops in proximity (<300m)  
prox300 <- divvy_station300 %>%
  filter(prox300 == 1)

# CTA arrivals to and departures from CTA stops that are in proximity(<300m) with Divvy stations 
cta_arrivals300             <- left_join(prox300, cta_arrivals) %>% select(-name)
colnames(cta_arrivals300)   <- c('to_station_id', colnames(cta_arrivals300)[2:6])
cta_departures300           <- left_join(prox300, cta_departures) %>% select(-name)
colnames(cta_departures300) <- c('from_station_id', colnames(cta_departures300)[2:6])

# Use smaller samples (joined data gets too large!)
# from300_sample       <- sample_n(divvy_from300, 10000)
# to300_sample         <- sample_n(divvy_to300, 10000)
# divvy_from300_sample <- multimodalFrom1(from300_sample, cta_departures300)
# divvy_to300_sample   <- multimodalTo1(to300_sample, cta_departures300)


##--------------------------------------------------------------------------------------------------##
## 6. SAVE OUTPUTS
##--------------------------------------------------------------------------------------------------##

# Outputs from Part 2
# write_feather(divvy_from50_sample, 'data/divvy_from50_sample.feather')
# write_feather(divvy_to50_sample, 'data/divvy_to50_sample.feather')

# Outputs from Part 3
# write_feather(divvy_from100_sample, 'data/divvy_from100_sample.feather')
# write_feather(divvy_to100_sample, 'data/divvy_to100_sample.feather')

# Outputs from Part 4
# write_feather(divvy_from200_sample, 'data/divvy_from200_sample.feather')
# write_feather(divvy_to200_sample, 'data/divvy_to200_sample.feather')

# Outputs from Part 5
# write_feather(divvy_from300_sample, 'data/divvy_from300_sample.feather')
# write_feather(divvy_to300_sample, 'data/divvy_to300_sample.feather')



# Clear the environment------------------------------------------------------------------------------#
rm(list=ls()) # clear the environment